import http from 'node:http';
import pg from 'pg';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import crypto from 'node:crypto';
import { readFile } from 'node:fs/promises';

const port = Number(process.env.PORT || 3000);
const secret = process.env.JWT_SECRET || 'development-only-change-me';
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL || 'postgres://scolaris:scolaris_dev@localhost:5432/scolaris' });
let schemaReady;
const ensureSchema = () => schemaReady ||= readFile(new URL('./schema.sql', import.meta.url), 'utf8').then(sql => pool.query(sql));
const json = (res,status,data) => { res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'content-type, authorization'}); res.end(JSON.stringify(data)); };
const csv = (res,name,rows) => { const quote=v=>`"${String(v??'').replaceAll('"','""')}"`; const output=rows.map(r=>r.map(quote).join(',')).join('\n'); res.writeHead(200,{'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="${name}"`,'access-control-allow-origin':'*'}); res.end('\ufeff'+output); };
const body = async req => { let raw=''; for await (const c of req) raw+=c; return raw ? JSON.parse(raw) : {}; };
const auth = req => { const token=req.headers.authorization?.replace(/^Bearer /,''); if(!token) throw Error('unauthorized'); return jwt.verify(token,secret); };
const route = (method,path) => `${method} ${path}`;

const handler=async(req,res)=>{
  if(req.method==='OPTIONS') return json(res,204,{});
  try {
    await ensureSchema();
    const url=new URL(req.url,'http://localhost');
    if(route(req.method,url.pathname)==='GET /api/health') { await pool.query('SELECT 1'); return json(res,200,{status:'ok',service:'scolaris-api'}); }
    if(route(req.method,url.pathname)==='POST /api/auth/bootstrap') {
      const b=await body(req); if(!b.schoolName||!b.name||!b.email||!b.password) return json(res,400,{error:'Champs requis manquants'});
      const client=await pool.connect(); try { await client.query('BEGIN');
        const school=(await client.query('INSERT INTO schools(name,slug,currency) VALUES($1,$2,$3) RETURNING *',[b.schoolName,b.slug||b.schoolName.toLowerCase().replace(/[^a-z0-9]+/g,'-'),b.currency||'XOF'])).rows[0];
        const hash=await bcrypt.hash(b.password,12); const user=(await client.query('INSERT INTO users(school_id,name,email,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING id,name,email,role',[school.id,b.name,b.email.toLowerCase(),hash,'owner'])).rows[0];
        await client.query('COMMIT'); return json(res,201,{school,user,token:jwt.sign({sub:user.id,schoolId:school.id,role:user.role},secret,{expiresIn:'8h'})});
      } catch(e){await client.query('ROLLBACK');throw e;} finally{client.release();}
    }
    if(route(req.method,url.pathname)==='POST /api/auth/login') { const b=await body(req); const q=await pool.query('SELECT * FROM users WHERE email=$1',[String(b.email||'').toLowerCase()]); const u=q.rows[0]; if(!u||!await bcrypt.compare(b.password||'',u.password_hash)) return json(res,401,{error:'Identifiants invalides'}); return json(res,200,{token:jwt.sign({sub:u.id,schoolId:u.school_id,role:u.role},secret,{expiresIn:'8h'}),user:{id:u.id,name:u.name,email:u.email,role:u.role}}); }
    if(req.method==='GET' && url.pathname.startsWith('/api/parent/')) { const token=url.pathname.split('/').pop(); const hash=crypto.createHash('sha256').update(token).digest('hex'); const access=(await pool.query('SELECT * FROM parent_portal_tokens WHERE token_hash=$1 AND revoked_at IS NULL AND expires_at>now()',[hash])).rows[0]; if(!access) return json(res,401,{error:'Lien invalide ou expiré'}); const guardian=(await pool.query('SELECT id,full_name,phone,email,preferred_language FROM guardians WHERE id=$1 AND school_id=$2',[access.guardian_id,access.school_id])).rows[0]; const students=(await pool.query(`SELECT s.id,s.matricule,s.first_name,s.last_name,s.class_name,COALESCE(json_agg(json_build_object('id',i.id,'label',i.label,'amountMinor',i.amount_minor::text,'paidMinor',COALESCE((SELECT sum(p.amount_minor) FROM payments p WHERE p.invoice_id=i.id),0)::text,'currency',i.currency,'dueDate',i.due_date,'status',i.status)) FILTER(WHERE i.id IS NOT NULL),'[]') invoices FROM student_guardians sg JOIN students s ON s.id=sg.student_id LEFT JOIN invoices i ON i.student_id=s.id WHERE sg.guardian_id=$1 AND s.school_id=$2 GROUP BY s.id ORDER BY s.first_name`,[access.guardian_id,access.school_id])).rows; return json(res,200,{guardian,students}); }
    const me=auth(req);
    if(route(req.method,url.pathname)==='GET /api/me') { const q=await pool.query('SELECT id,name,email,role FROM users WHERE id=$1 AND school_id=$2',[me.sub,me.schoolId]); return json(res,200,q.rows[0]); }
    if(route(req.method,url.pathname)==='GET /api/students') { const q=await pool.query('SELECT * FROM students WHERE school_id=$1 ORDER BY last_name,first_name',[me.schoolId]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='POST /api/students') { const b=await body(req); const q=await pool.query('INSERT INTO students(school_id,matricule,first_name,last_name,class_name,guardian_name,guardian_phone) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[me.schoolId,b.matricule,b.firstName,b.lastName,b.className,b.guardianName,b.guardianPhone]); return json(res,201,q.rows[0]); }
    if(route(req.method,url.pathname)==='GET /api/academic-years') { const q=await pool.query('SELECT * FROM academic_years WHERE school_id=$1 ORDER BY starts_on DESC',[me.schoolId]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='POST /api/academic-years') { const b=await body(req); const q=await pool.query('INSERT INTO academic_years(school_id,label,starts_on,ends_on,is_current) VALUES($1,$2,$3,$4,$5) RETURNING *',[me.schoolId,b.label,b.startsOn,b.endsOn,Boolean(b.isCurrent)]); return json(res,201,q.rows[0]); }
    if(route(req.method,url.pathname)==='GET /api/classes') { const q=await pool.query('SELECT c.*,a.label academic_year FROM classes c JOIN academic_years a ON a.id=c.academic_year_id WHERE c.school_id=$1 ORDER BY c.name',[me.schoolId]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='POST /api/classes') { const b=await body(req); const q=await pool.query('INSERT INTO classes(school_id,academic_year_id,name,level,capacity) VALUES($1,$2,$3,$4,$5) RETURNING *',[me.schoolId,b.academicYearId,b.name,b.level,b.capacity||null]); return json(res,201,q.rows[0]); }
    if(route(req.method,url.pathname)==='GET /api/guardians') { const q=await pool.query('SELECT * FROM guardians WHERE school_id=$1 ORDER BY full_name',[me.schoolId]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='POST /api/guardians') { const b=await body(req); const q=await pool.query('INSERT INTO guardians(school_id,full_name,phone,email,preferred_language) VALUES($1,$2,$3,$4,$5) RETURNING *',[me.schoolId,b.fullName,b.phone,b.email,b.preferredLanguage||'fr']); return json(res,201,q.rows[0]); }
    if(route(req.method,url.pathname)==='POST /api/enrollments') { const b=await body(req); const client=await pool.connect(); try { await client.query('BEGIN'); const e=(await client.query('INSERT INTO enrollments(school_id,student_id,class_id,academic_year_id,status) VALUES($1,$2,$3,$4,$5) RETURNING *',[me.schoolId,b.studentId,b.classId,b.academicYearId,b.status||'active'])).rows[0]; await client.query('UPDATE students SET class_name=(SELECT name FROM classes WHERE id=$1 AND school_id=$2) WHERE id=$3 AND school_id=$2',[b.classId,me.schoolId,b.studentId]); await client.query('COMMIT'); return json(res,201,e); } catch(e){await client.query('ROLLBACK');throw e;} finally{client.release();} }
    if(route(req.method,url.pathname)==='POST /api/student-guardians') { const b=await body(req); const q=await pool.query('INSERT INTO student_guardians(student_id,guardian_id,relationship,is_primary) SELECT $1,$2,$3,$4 WHERE EXISTS(SELECT 1 FROM students WHERE id=$1 AND school_id=$5) AND EXISTS(SELECT 1 FROM guardians WHERE id=$2 AND school_id=$5) RETURNING *',[b.studentId,b.guardianId,b.relationship||'parent',Boolean(b.isPrimary),me.schoolId]); return q.rows[0]?json(res,201,q.rows[0]):json(res,404,{error:'Élève ou parent introuvable'}); }
    if(route(req.method,url.pathname)==='GET /api/invoices') { const q=await pool.query('SELECT i.*,s.first_name,s.last_name,s.matricule,COALESCE((SELECT sum(p.amount_minor) FROM payments p WHERE p.invoice_id=i.id),0)::text paid_minor FROM invoices i JOIN students s ON s.id=i.student_id WHERE i.school_id=$1 ORDER BY i.due_date',[me.schoolId]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='POST /api/invoices') { const b=await body(req); const q=await pool.query('INSERT INTO invoices(school_id,student_id,label,amount_minor,currency,due_date) SELECT $1,$2,$3,$4,$5,$6 WHERE EXISTS(SELECT 1 FROM students WHERE id=$2 AND school_id=$1) RETURNING *',[me.schoolId,b.studentId,b.label,String(b.amountMinor),b.currency,b.dueDate]); return q.rows[0]?json(res,201,q.rows[0]):json(res,404,{error:'Élève introuvable'}); }
    if(route(req.method,url.pathname)==='POST /api/payments') { const b=await body(req); const client=await pool.connect(); try { await client.query('BEGIN'); const inv=(await client.query('SELECT * FROM invoices WHERE id=$1 AND school_id=$2 FOR UPDATE',[b.invoiceId,me.schoolId])).rows[0]; if(!inv) return json(res,404,{error:'Échéance introuvable'}); if(inv.currency!==b.currency) return json(res,400,{error:'La devise doit correspondre à celle de l’échéance'}); const p=(await client.query('INSERT INTO payments(school_id,student_id,invoice_id,amount_minor,currency,method,reference) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[me.schoolId,inv.student_id,inv.id,String(b.amountMinor),b.currency,b.method,b.reference])).rows[0]; const total=BigInt((await client.query('SELECT COALESCE(sum(amount_minor),0)::text total FROM payments WHERE invoice_id=$1',[inv.id])).rows[0].total); const status=total>=BigInt(inv.amount_minor)?'paid':'partial'; await client.query('UPDATE invoices SET status=$1 WHERE id=$2',[status,inv.id]); const receiptNumber=`SCP-${new Date().getUTCFullYear()}-${String(Date.now()).slice(-8)}`; const receipt=(await client.query('INSERT INTO receipts(school_id,payment_id,number) VALUES($1,$2,$3) RETURNING *',[me.schoolId,p.id,receiptNumber])).rows[0]; await client.query('INSERT INTO audit_logs(school_id,user_id,action,entity,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[me.schoolId,me.sub,'payment.created','payment',p.id,JSON.stringify({amountMinor:b.amountMinor,currency:b.currency,reference:b.reference})]); await client.query('COMMIT'); return json(res,201,{payment:p,receipt,invoiceStatus:status}); } catch(e){await client.query('ROLLBACK');throw e;} finally{client.release();} }
    if(route(req.method,url.pathname)==='GET /api/receipts') { const q=await pool.query('SELECT r.*,p.amount_minor,p.currency,p.method,p.reference,s.first_name,s.last_name FROM receipts r JOIN payments p ON p.id=r.payment_id JOIN students s ON s.id=p.student_id WHERE r.school_id=$1 ORDER BY r.issued_at DESC',[me.schoolId]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='GET /api/collections/overdue') { const q=await pool.query(`SELECT i.id,i.label,i.amount_minor::text,i.currency,i.due_date,i.status,s.matricule,s.first_name,s.last_name,COALESCE(sum(p.amount_minor),0)::text paid_minor,(i.amount_minor-COALESCE(sum(p.amount_minor),0))::text balance_minor FROM invoices i JOIN students s ON s.id=i.student_id LEFT JOIN payments p ON p.invoice_id=i.id WHERE i.school_id=$1 AND i.status IN ('unpaid','partial') AND i.due_date<CURRENT_DATE GROUP BY i.id,s.id ORDER BY i.due_date`,[me.schoolId]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='POST /api/reminders') { const b=await body(req); const q=await pool.query(`INSERT INTO reminders(school_id,guardian_id,invoice_id,channel,message,scheduled_at) SELECT $1,$2,$3,$4,$5,COALESCE($6::timestamptz,now()) WHERE EXISTS(SELECT 1 FROM guardians WHERE id=$2 AND school_id=$1) AND EXISTS(SELECT 1 FROM invoices WHERE id=$3 AND school_id=$1) RETURNING *`,[me.schoolId,b.guardianId,b.invoiceId,b.channel,b.message,b.scheduledAt||null]); return q.rows[0]?json(res,201,q.rows[0]):json(res,404,{error:'Parent ou échéance introuvable'}); }
    if(route(req.method,url.pathname)==='GET /api/reminders') { const q=await pool.query('SELECT r.*,g.full_name guardian_name,i.label invoice_label FROM reminders r JOIN guardians g ON g.id=r.guardian_id JOIN invoices i ON i.id=r.invoice_id WHERE r.school_id=$1 ORDER BY r.scheduled_at DESC',[me.schoolId]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='POST /api/parent-links') { const b=await body(req); const exists=(await pool.query('SELECT 1 FROM guardians WHERE id=$1 AND school_id=$2',[b.guardianId,me.schoolId])).rowCount; if(!exists) return json(res,404,{error:'Parent introuvable'}); const token=crypto.randomBytes(32).toString('base64url'); const hash=crypto.createHash('sha256').update(token).digest('hex'); const hours=Math.min(Math.max(Number(b.expiresInHours)||72,1),720); const record=(await pool.query(`INSERT INTO parent_portal_tokens(school_id,guardian_id,token_hash,expires_at) VALUES($1,$2,$3,now()+($4||' hours')::interval) RETURNING id,guardian_id,expires_at`,[me.schoolId,b.guardianId,hash,String(hours)])).rows[0]; return json(res,201,{...record,token,path:`/parent/${token}`}); }
    if(route(req.method,url.pathname)==='GET /api/exports/payments.csv') { const q=await pool.query('SELECT p.paid_at,s.matricule,s.first_name,s.last_name,p.amount_minor,p.currency,p.method,p.reference,r.number receipt FROM payments p JOIN students s ON s.id=p.student_id LEFT JOIN receipts r ON r.payment_id=p.id WHERE p.school_id=$1 ORDER BY p.paid_at DESC',[me.schoolId]); return csv(res,'paiements.csv',[['Date','Matricule','Prénom','Nom','Montant mineur','Devise','Méthode','Référence','Reçu'],...q.rows.map(x=>[x.paid_at.toISOString(),x.matricule,x.first_name,x.last_name,x.amount_minor,x.currency,x.method,x.reference,x.receipt])]); }
    if(route(req.method,url.pathname)==='GET /api/dashboard') { const q=await pool.query(`SELECT COALESCE(sum(amount_minor),0)::text expected,COALESCE(sum(amount_minor) FILTER(WHERE status='paid'),0)::text paid,COUNT(*) FILTER(WHERE status!='paid')::int unpaid_count FROM invoices WHERE school_id=$1`,[me.schoolId]); return json(res,200,q.rows[0]); }
    return json(res,404,{error:'Route introuvable'});
  } catch(e){ console.error(e); return json(res,e.message==='unauthorized'?401:500,{error:e.message==='unauthorized'?'Authentification requise':'Erreur interne'}); }
};

if (!process.env.VERCEL) {
  http.createServer(handler).listen(port,'0.0.0.0',()=>console.log(`SCOLARIS API : http://localhost:${port}`));
}

export default handler;
