import http from 'node:http';
import pg from 'pg';
import crypto from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { unzipSync } from 'fflate';
import readXlsxFile from 'read-excel-file/node';
import {
  clearSessionCookie,
  hasPermission,
  hasSpreadsheetFormula,
  isAllowedBrowserOrigin,
  loginAttemptKeys,
  normalizeEmail,
  pagination,
  permissionFor,
  positiveInteger,
  quoteCsv,
  safeText,
  validateJsonValue,
} from './security.js';
import { createAuthService } from './auth-service.js';

const port = Number(process.env.PORT || 3000);
const production = process.env.NODE_ENV === 'production' || ['preview','production'].includes(process.env.VERCEL_ENV);
if (production && (!process.env.JWT_SECRET || process.env.JWT_SECRET.length < 32)) throw new Error('JWT_SECRET doit contenir au moins 32 caractères');
if (production && !process.env.DATABASE_URL) throw new Error('DATABASE_URL est obligatoire');
const secret = process.env.JWT_SECRET || 'local-development-secret-change-me-only';
const databaseUrl = new URL(process.env.DATABASE_URL || 'postgres://scolaris:scolaris_dev@localhost:5432/scolaris');
if (production && ['prefer', 'require', 'verify-ca'].includes(databaseUrl.searchParams.get('sslmode'))) databaseUrl.searchParams.set('sslmode', 'verify-full');
const pool = new pg.Pool({ connectionString: databaseUrl.toString(), max: 10, idleTimeoutMillis: 30_000, connectionTimeoutMillis: 5_000 });
const allowedOrigins = String(process.env.ALLOWED_ORIGINS || '').split(',').map(x=>x.trim()).filter(Boolean);
const mfaEnforcement = String(process.env.MFA_ENFORCEMENT || 'off').toLowerCase();
if (!['off','privileged','all'].includes(mfaEnforcement)) throw new Error('MFA_ENFORCEMENT invalide');
if (production && mfaEnforcement !== 'off' && !process.env.MFA_ENCRYPTION_KEY) throw new Error('MFA_ENCRYPTION_KEY est obligatoire lorsque la MFA est appliquée');
let schemaReady;
const ensureSchema = () => schemaReady ||= readFile(new URL('./schema.sql', import.meta.url), 'utf8').then(sql => pool.query(sql));
const authService = createAuthService({pool,secret,production,mfaEncryptionKey:process.env.MFA_ENCRYPTION_KEY,mfaIssuer:process.env.MFA_ISSUER || 'SCOLARIS PAY',passwordResetWebhookUrl:process.env.PASSWORD_RESET_WEBHOOK_URL,passwordResetWebhookSecret:process.env.PASSWORD_RESET_WEBHOOK_SECRET});
const commonHeaders = {'strict-transport-security':'max-age=63072000; includeSubDomains; preload','x-content-type-options':'nosniff','referrer-policy':'no-referrer','cache-control':'no-store, private, max-age=0','pragma':'no-cache','permissions-policy':'camera=(), microphone=(), geolocation=()','cross-origin-opener-policy':'same-origin','cross-origin-resource-policy':'same-origin','x-frame-options':'DENY','x-robots-tag':'noindex, nofollow, noarchive'};
const json = (res,status,data,headers={}) => { res.writeHead(status,{'content-type':'application/json; charset=utf-8',...commonHeaders,...headers}); res.end(status===204?'':JSON.stringify(data)); };
const csv = (res,name,rows) => { const output=rows.map(r=>r.map(quoteCsv).join(',')).join('\r\n'); res.writeHead(200,{'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="${name}"`,...commonHeaders}); res.end('\ufeff'+output); };
const body = async req => { if(!String(req.headers['content-type']||'').toLowerCase().startsWith('application/json'))throw Error('unsupported_media');let raw='';for await(const c of req){raw+=c;if(Buffer.byteLength(raw)>4_500_000)throw Error('body_too_large')}let parsed={};try{parsed=raw?JSON.parse(raw):{}}catch{throw Error('invalid_body')}validateJsonValue(parsed);return parsed; };
const isPlatformAdmin = async me => Boolean(me?.platformAdmin);
const auth = authService.authenticate;
const createSession = authService.issueSession;
const loginStatus = async keys => (await pool.query('SELECT attempts,locked_until FROM login_attempts WHERE attempt_key=ANY($1::text[]) AND locked_until>now() ORDER BY locked_until DESC LIMIT 1',[Object.values(keys)])).rows[0];
const registerLoginFailure = async keys => {
  for (const key of Object.values(keys)) {
    const firstThreshold=key.startsWith('address:')?30:key.startsWith('device:')?15:5;
    await pool.query(`INSERT INTO login_attempts(attempt_key,attempts,first_attempt_at,locked_until,updated_at) VALUES($1,1,now(),NULL,now())
      ON CONFLICT(attempt_key) DO UPDATE SET attempts=CASE WHEN login_attempts.first_attempt_at<now()-interval '1 hour' THEN 1 ELSE login_attempts.attempts+1 END,first_attempt_at=CASE WHEN login_attempts.first_attempt_at<now()-interval '1 hour' THEN now() ELSE login_attempts.first_attempt_at END,locked_until=CASE WHEN (CASE WHEN login_attempts.first_attempt_at<now()-interval '1 hour' THEN 1 ELSE login_attempts.attempts+1 END)>=$4 THEN now()+interval '1 hour' WHEN (CASE WHEN login_attempts.first_attempt_at<now()-interval '1 hour' THEN 1 ELSE login_attempts.attempts+1 END)>=$3 THEN now()+interval '15 minutes' WHEN (CASE WHEN login_attempts.first_attempt_at<now()-interval '1 hour' THEN 1 ELSE login_attempts.attempts+1 END)>=$2 THEN now()+interval '1 minute' ELSE login_attempts.locked_until END,updated_at=now()`,[key,firstThreshold,firstThreshold+3,firstThreshold+7]);
  }
};
const route = (method,path) => `${method} ${path}`;
const identifier = value => safeText(value,{min:36,max:36,pattern:/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i});
const isoDate = value => {const text=safeText(value,{min:10,max:10,pattern:/^\d{4}-\d{2}-\d{2}$/}),date=new Date(`${text}T00:00:00.000Z`);if(Number.isNaN(date.getTime())||date.toISOString().slice(0,10)!==text)throw Error('invalid_body');return text};
const isoTimestamp = value => {const text=safeText(value,{min:10,max:40}),date=new Date(text);if(Number.isNaN(date.getTime()))throw Error('invalid_body');return date.toISOString()};
const currencyCode = value => safeText(value,{min:3,max:3,pattern:/^[A-Za-z]{3}$/}).toUpperCase();
const emailAddress = value => {const text=normalizeEmail(value);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(text))throw Error('invalid_body');return text};
const oneOf = (value,allowed) => {const text=String(value??'');if(!allowed.includes(text))throw Error('invalid_body');return text};
const parseCsv = text => { const rows=[]; let row=[],cell='',quoted=false; const delimiter=(text.split(/\r?\n/,1)[0].match(/;/g)||[]).length>(text.split(/\r?\n/,1)[0].match(/,/g)||[]).length?';':','; for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(ch==='"'){quoted=!quoted;}else if(ch===delimiter&&!quoted){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>String(v).trim()))rows.push(row);row=[];cell='';}else cell+=ch;}if(cell||row.length){row.push(cell);rows.push(row)}return rows;};
const normalizeHeader = value => String(value??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const allocateMatricules = async (client,schoolId,count) => { if(!count)return[];const q=await client.query('INSERT INTO school_counters(school_id,student_next) VALUES($1,$2::bigint+1) ON CONFLICT(school_id) DO UPDATE SET student_next=school_counters.student_next+$2::bigint RETURNING (student_next-$2::bigint)::text start',[schoolId,count]);const start=BigInt(q.rows[0].start),year=new Date().getUTCFullYear();return Array.from({length:count},(_,i)=>`ELV-${year}-${String(start+BigInt(i)).padStart(5,'0')}`);};

const handler=async(req,res)=>{
  try {
    await ensureSchema();
    const url=new URL(req.url,'http://localhost');
    if(!['GET','HEAD','OPTIONS'].includes(req.method)&&!isAllowedBrowserOrigin(req,allowedOrigins))return json(res,403,{error:'Requête refusée'});
    if(req.method==='OPTIONS') {
      if(!isAllowedBrowserOrigin(req,allowedOrigins))return json(res,403,{error:'Requête refusée'});
      return json(res,204,{}, {'allow':'GET, HEAD, POST, PUT, DELETE, OPTIONS'});
    }
    if(route(req.method,url.pathname)==='GET /api/health') { await pool.query('SELECT 1'); return json(res,200,{status:'ok',service:'scolaris-api'}); }
    if(route(req.method,url.pathname)==='GET /api/cron/subscriptions') { if(!process.env.CRON_SECRET||req.headers.authorization!==`Bearer ${process.env.CRON_SECRET}`) return json(res,401,{error:'Non autorisé'}); const q=await pool.query("UPDATE schools SET subscription_status='suspended',suspended_at=COALESCE(suspended_at,now()) WHERE subscription_due_date<CURRENT_DATE AND subscription_status='active' RETURNING id"); return json(res,200,{ok:true,suspended:q.rowCount}); }
    if(route(req.method,url.pathname)==='GET /api/cron/security-alerts') { if(!process.env.CRON_SECRET||req.headers.authorization!==`Bearer ${process.env.CRON_SECRET}`)return json(res,401,{error:'Non autorisé'});if(!process.env.SECURITY_ALERT_WEBHOOK_URL)return json(res,200,{ok:true,configured:false});const endpoint=new URL(process.env.SECURITY_ALERT_WEBHOOK_URL);if(endpoint.protocol!=='https:')throw Error('alerting_unavailable');const events=(await pool.query("SELECT event_type,severity,outcome,count(*)::int total FROM security_events WHERE created_at>now()-interval '15 minutes' AND severity IN ('warning','critical') GROUP BY event_type,severity,outcome ORDER BY severity,event_type")).rows;if(events.length){const response=await fetch(endpoint,{method:'POST',redirect:'error',signal:AbortSignal.timeout(5000),headers:{'content-type':'application/json',...(process.env.SECURITY_ALERT_WEBHOOK_SECRET?{authorization:`Bearer ${process.env.SECURITY_ALERT_WEBHOOK_SECRET}`}:{})},body:JSON.stringify({service:'scolaris-pay',windowMinutes:15,events})});if(!response.ok)throw Error('alerting_unavailable')}return json(res,200,{ok:true,configured:true,alerts:events.length}); }
    if(route(req.method,url.pathname)==='POST /api/auth/bootstrap') {
      if(!process.env.BOOTSTRAP_SECRET||req.headers['x-bootstrap-secret']!==process.env.BOOTSTRAP_SECRET)return json(res,404,{error:'Ressource introuvable'});
      if(Number((await pool.query('SELECT count(*)::int total FROM users')).rows[0].total)>0) return json(res,403,{error:'Les inscriptions publiques sont fermées. Contactez SCOLARIS PAY.'});
		      const b=await body(req),schoolName=safeText(b.schoolName,{min:2,max:180}),ownerName=safeText(b.name,{min:2,max:180}),email=emailAddress(b.email),currency=currencyCode(b.currency||'XOF');
		      const slug=safeText(b.slug||schoolName.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),{min:2,max:100,pattern:/^[a-z0-9]+(?:-[a-z0-9]+)*$/});
	      const client=await pool.connect(); try { await client.query('BEGIN');
	        const school=(await client.query('INSERT INTO schools(name,slug,currency) VALUES($1,$2,$3) RETURNING id,name,slug,currency,subscription_status,subscription_due_date,created_at',[schoolName,slug,currency])).rows[0];
		        const hash=await authService.hashPassword(b.password); const user=(await client.query('INSERT INTO users(school_id,name,email,password_hash,role,is_platform_admin) VALUES($1,$2,$3,$4,$5,true) RETURNING id,school_id,name,email,role,is_platform_admin',[school.id,ownerName,email,hash,'owner'])).rows[0];
        await client.query('COMMIT');await createSession(req,res,user);return json(res,201,{user:{id:user.id,name:user.name,role:user.role,platformAdmin:true}});
      } catch(e){await client.query('ROLLBACK');throw e;} finally{client.release();}
    }
	    if(route(req.method,url.pathname)==='POST /api/auth/login') {
	      const b=await body(req),email=normalizeEmail(b.email),password=String(b.password||''),keys=loginAttemptKeys(req,email,secret),state=await loginStatus(keys);
	      if(state?.locked_until){
	        await authService.securityEvent(req,{type:'authentication.rate_limited',severity:'warning',outcome:'denied',metadata:{scope:'login'}});
	        return json(res,429,{error:'Connexion impossible. Réessayez plus tard.'},{'retry-after':'60'});
	      }
	      const u=(await pool.query(`SELECT u.id,u.school_id,u.name,u.email,u.password_hash,u.role,u.is_platform_admin,u.is_active,m.enabled_at mfa_enabled
	        FROM users u LEFT JOIN user_mfa m ON m.user_id=u.id WHERE u.email=$1`,[email])).rows[0];
	      const verification=await authService.verifyPassword(u?.password_hash,password);
	      if(!u||!u.is_active||!verification.valid){
	        await registerLoginFailure(keys);
	        await authService.securityEvent(req,{type:'authentication.failed',severity:'warning',outcome:'denied',userId:u?.id||null,schoolId:u?.school_id||null,metadata:{reason:'invalid_credentials'}});
	        return json(res,401,{error:'Connexion impossible. Vérifiez vos informations.'});
	      }
	      if(!u.is_platform_admin){
	        await pool.query("UPDATE schools SET subscription_status='suspended',suspended_at=COALESCE(suspended_at,now()) WHERE id=$1 AND subscription_due_date<CURRENT_DATE AND subscription_status='active'",[u.school_id]);
	        const school=(await pool.query('SELECT subscription_status FROM schools WHERE id=$1',[u.school_id])).rows[0];
	        if(school?.subscription_status==='suspended'){
	          await registerLoginFailure(keys);
	          await authService.securityEvent(req,{type:'authentication.failed',severity:'warning',outcome:'denied',userId:u.id,schoolId:u.school_id,metadata:{reason:'account_unavailable'}});
	          return json(res,401,{error:'Connexion impossible. Vérifiez vos informations.'});
	        }
	      }
	      if(verification.needsRehash){
	        const upgraded=await authService.hashPassword(password);
	        await pool.query('UPDATE users SET password_hash=$1 WHERE id=$2 AND password_hash=$3',[upgraded,u.id,u.password_hash]);
	      }
	      await pool.query('DELETE FROM login_attempts WHERE attempt_key=ANY($1::text[])',[Object.values(keys).filter(key=>!key.startsWith('address:'))]);
	      if(u.mfa_enabled){
	        await authService.createMfaChallenge(req,res,u);
	        await authService.securityEvent(req,{type:'authentication.password_succeeded',outcome:'challenge',userId:u.id,schoolId:u.school_id,metadata:{mfa:true}});
	        return json(res,202,{mfaRequired:true,error:'Code de vérification requis'});
	      }
	      await createSession(req,res,u);
	      await authService.securityEvent(req,{type:'authentication.succeeded',outcome:'success',userId:u.id,schoolId:u.school_id,metadata:{mfa:false}});
	      const privileged=Boolean(u.is_platform_admin)||['owner','director','accountant'].includes(u.role);
	      return json(res,200,{user:{id:u.id,name:u.name,role:u.role,platformAdmin:u.is_platform_admin},mfaEnrollmentRequired:mfaEnforcement==='all'||(mfaEnforcement==='privileged'&&privileged)});
	    }
	    if(route(req.method,url.pathname)==='POST /api/auth/mfa') { const b=await body(req);const u=await authService.completeMfaChallenge(req,res,b.code);return json(res,200,{user:{id:u.id,name:u.name,role:u.role,platformAdmin:u.is_platform_admin}}); }
	    if(route(req.method,url.pathname)==='POST /api/auth/password-reset/request') { const b=await body(req);const email=normalizeEmail(b.email);if(email&&email.length<=254)await authService.requestPasswordReset(req,email);return json(res,202,{message:'Si ce compte peut être récupéré, les instructions seront envoyées.'}); }
	    if(route(req.method,url.pathname)==='POST /api/auth/password-reset/confirm') { const b=await body(req);await authService.resetPassword(req,res,String(b.token||''),String(b.password||''));return json(res,200,{message:'Mot de passe mis à jour. Reconnectez-vous.'}); }
    if(req.method==='GET' && url.pathname.startsWith('/api/parent/')) return json(res,410,{error:'Les codes d’accès ne sont plus acceptés dans les URL'});
    if(route(req.method,url.pathname)==='POST /api/parent/access') { const b=await body(req);const token=String(b.accessCode||'');if(token.length<32)return json(res,401,{error:'Accès impossible'});const hash=crypto.createHash('sha256').update(token).digest('hex');const access=(await pool.query('SELECT guardian_id,school_id FROM parent_portal_tokens WHERE token_hash=$1 AND revoked_at IS NULL AND expires_at>now()',[hash])).rows[0];if(!access)return json(res,401,{error:'Accès impossible'});const guardian=(await pool.query('SELECT id,full_name,preferred_language FROM guardians WHERE id=$1 AND school_id=$2',[access.guardian_id,access.school_id])).rows[0];const students=(await pool.query(`SELECT s.id,s.matricule,s.first_name,s.last_name,s.class_name,COALESCE(json_agg(json_build_object('id',i.id,'label',i.label,'amountMinor',i.amount_minor::text,'paidMinor',COALESCE((SELECT sum(p.amount_minor) FROM payments p WHERE p.invoice_id=i.id AND p.school_id=$2),0)::text,'currency',i.currency,'dueDate',i.due_date,'status',i.status)) FILTER(WHERE i.id IS NOT NULL),'[]') invoices FROM student_guardians sg JOIN students s ON s.id=sg.student_id LEFT JOIN invoices i ON i.student_id=s.id AND i.school_id=$2 WHERE sg.guardian_id=$1 AND s.school_id=$2 GROUP BY s.id ORDER BY s.first_name`,[access.guardian_id,access.school_id])).rows;return json(res,200,{guardian,students}); }
		    const me=await auth(req,res);
		    const platform=await isPlatformAdmin(me);
		    const privileged=platform||['owner','director','accountant'].includes(me.role);
		    const mfaEnrollmentRequired=mfaEnforcement==='all'||(mfaEnforcement==='privileged'&&privileged);
	    if(route(req.method,url.pathname)==='POST /api/auth/logout'){await pool.query('UPDATE sessions SET revoked_at=now() WHERE id=$1 AND user_id=$2',[me.sid,me.sub]);await authService.securityEvent(req,{type:'session.logout',outcome:'success',userId:me.sub,schoolId:me.schoolId});res.setHeader('set-cookie',clearSessionCookie({secure:production}));return json(res,200,{ok:true});}
	    if(route(req.method,url.pathname)==='POST /api/auth/reauthenticate'){const b=await body(req);if(!await authService.reauthenticate(req,me,b.password))return json(res,401,{error:'Réauthentification impossible'});return json(res,200,{ok:true,recentForSeconds:600});}
	    if(route(req.method,url.pathname)==='POST /api/auth/password/change'){const b=await body(req);await authService.changePassword(req,res,me,b.currentPassword,b.newPassword);return json(res,200,{ok:true});}
	    if(route(req.method,url.pathname)==='GET /api/auth/sessions')return json(res,200,{sessions:await authService.listSessions(me),maximum:5});
	    if(req.method==='DELETE'&&/^\/api\/auth\/sessions\/[^/]+$/.test(url.pathname)){const id=url.pathname.split('/').pop();if(!await authService.revokeSession(req,me,id))return json(res,404,{error:'Session introuvable'});if(id===me.sid)res.setHeader('set-cookie',clearSessionCookie({secure:production}));return json(res,200,{revoked:true,current:id===me.sid});}
	    if(route(req.method,url.pathname)==='POST /api/auth/mfa/setup'){const result=await authService.beginMfaSetup(req,me);return json(res,200,result);}
	    if(route(req.method,url.pathname)==='POST /api/auth/mfa/confirm'){const b=await body(req);const recoveryCodes=await authService.confirmMfaSetup(req,me,b.code);return json(res,200,{recoveryCodes});}
		    if(route(req.method,url.pathname)==='DELETE /api/auth/mfa'){const b=await body(req);await authService.disableMfa(req,me,b.password);return json(res,200,{disabled:true});}
		    if(route(req.method,url.pathname)==='GET /api/me') { const q=await pool.query('SELECT u.id,u.name,u.email,u.role,s.name school_name FROM users u JOIN schools s ON s.id=u.school_id WHERE u.id=$1 AND u.school_id=$2',[me.sub,me.schoolId]); return json(res,200,{...q.rows[0],platformAdmin:platform,mfaEnabled:me.mfaEnabled,mfaEnrollmentRequired}); }
	    if(req.method==='GET' && ['/app','/api/private/app'].includes(url.pathname)){const html=await readFile(new URL('./private-app.html',import.meta.url),'utf8');res.writeHead(200,{'content-type':'text/html; charset=utf-8',...commonHeaders,'x-robots-tag':'noindex, nofollow, noarchive','content-security-policy':"default-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'sha256-c0nB5zwWtqoe5CKZ/yvaSLgdZvul27naavNvcnSgsCU='; connect-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests"});return res.end(html);}
		    if(mfaEnrollmentRequired&&!me.mfaEnabled)return json(res,428,{error:'Activez la vérification en deux étapes avant de continuer.',code:'mfa_enrollment_required'});
	    const needed=permissionFor(req.method,url.pathname);if(!platform&&needed&&!hasPermission(me.role,needed)){await authService.securityEvent(req,{type:'authorization.denied',severity:'warning',outcome:'denied',userId:me.sub,schoolId:me.schoolId,metadata:{permission:needed,method:req.method,route:url.pathname.replace(/[0-9a-f-]{16,}/gi,':id')}});return json(res,403,{error:'Action non autorisée'});}
    if(!platform){await pool.query("UPDATE schools SET subscription_status='suspended',suspended_at=COALESCE(suspended_at,now()) WHERE id=$1 AND subscription_due_date<CURRENT_DATE AND subscription_status='active'",[me.schoolId]);const access=(await pool.query('SELECT subscription_status FROM schools WHERE id=$1',[me.schoolId])).rows[0];if(access?.subscription_status==='suspended')return json(res,403,{error:'Compte suspendu pour abonnement impayé. Contactez SCOLARIS PAY.'});}
    if(route(req.method,url.pathname)==='GET /api/platform/clients') { if(!platform) return json(res,403,{error:'Accès super-administrateur requis'}); const {limit,offset}=pagination(url.searchParams,{defaultLimit:50,maxLimit:100});const q=await pool.query(`SELECT s.id,s.name,s.slug,s.currency,s.created_at,s.subscription_status,s.subscription_due_date,s.suspended_at,s.deletion_requested_at,u.name owner_name,u.email owner_email,COALESCE(u.is_platform_admin,false) platform_admin,(SELECT count(*)::int FROM students st WHERE st.school_id=s.id) student_count FROM schools s LEFT JOIN LATERAL(SELECT id,name,email,is_platform_admin FROM users WHERE school_id=s.id AND role='owner' ORDER BY is_platform_admin DESC,created_at LIMIT 1) u ON true ORDER BY s.created_at DESC LIMIT $1 OFFSET $2`,[limit,offset]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='POST /api/platform/clients') { if(!platform) return json(res,403,{error:'Accès super-administrateur requis'}); authService.requireRecentAuthentication(me); const b=await body(req),schoolName=safeText(b.schoolName,{min:2,max:180}),ownerName=safeText(b.name,{min:2,max:180}),email=emailAddress(b.email),currency=currencyCode(b.currency||'XOF'),subscriptionDueDate=isoDate(b.subscriptionDueDate);const client=await pool.connect(); try{await client.query('BEGIN');const base=schoolName.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'ecole';const slug=base.slice(0,90)+'-'+crypto.randomBytes(3).toString('hex');const school=(await client.query("INSERT INTO schools(name,slug,currency,subscription_status,subscription_due_date) VALUES($1,$2,$3,'active',$4) RETURNING id,name,slug,currency,subscription_status,subscription_due_date",[schoolName,slug,currency,subscriptionDueDate])).rows[0];const hash=await authService.hashPassword(b.password);const owner=(await client.query('INSERT INTO users(school_id,name,email,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING id,name,email,role',[school.id,ownerName,email,hash,'owner'])).rows[0];await client.query('INSERT INTO audit_logs(school_id,user_id,action,entity,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[me.schoolId,me.sub,'client.created','school',school.id,JSON.stringify({dueDate:subscriptionDueDate})]);await client.query('COMMIT');await authService.securityEvent(req,{type:'platform.client_created',severity:'warning',outcome:'success',userId:me.sub,schoolId:me.schoolId,metadata:{targetSchoolId:school.id}});return json(res,201,{school,owner});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()} }
   if(req.method==='PUT' && /^\/api\/platform\/clients\/[^/]+\/subscription$/.test(url.pathname)) { if(!platform) return json(res,403,{error:'Accès super-administrateur requis'});authService.requireRecentAuthentication(me); const id=identifier(url.pathname.split('/')[4]); const b=await body(req),action=oneOf(b.action,['suspend','reactivate','renew']); const target=(await pool.query(`SELECT s.id,COALESCE(bool_or(u.is_platform_admin),false) platform_admin FROM schools s LEFT JOIN users u ON u.school_id=s.id WHERE s.id=$1 GROUP BY s.id`,[id])).rows[0]; if(!target)return json(res,404,{error:'Client introuvable'});if(target.platform_admin)return json(res,400,{error:'Le compte super-administrateur ne peut pas être suspendu'});const active=action==='reactivate'||action==='renew',subscriptionDueDate=active?isoDate(b.subscriptionDueDate):null;const q=await pool.query("UPDATE schools SET subscription_status=$1,subscription_due_date=COALESCE($2::date,subscription_due_date),suspended_at=CASE WHEN $1='suspended' THEN now() ELSE NULL END WHERE id=$3 RETURNING id,name,slug,currency,subscription_status,subscription_due_date,suspended_at",[active?'active':'suspended',subscriptionDueDate,id]);await pool.query('INSERT INTO audit_logs(school_id,user_id,action,entity,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[me.schoolId,me.sub,action==='renew'?'client.renewed':active?'client.reactivated':'client.suspended','school',id,JSON.stringify({dueDate:subscriptionDueDate})]);await authService.securityEvent(req,{type:'platform.subscription_changed',severity:'warning',outcome:'success',userId:me.sub,schoolId:me.schoolId,metadata:{targetSchoolId:id,action}});return json(res,200,q.rows[0]); }
    if(req.method==='DELETE' && /^\/api\/platform\/clients\/[^/]+$/.test(url.pathname)) { if(!platform)return json(res,403,{error:'Accès super-administrateur requis'});authService.requireRecentAuthentication(me);const id=identifier(url.pathname.split('/').pop()),b=await body(req);const target=(await pool.query(`SELECT s.id,s.name,COALESCE(bool_or(u.is_platform_admin),false) platform_admin FROM schools s LEFT JOIN users u ON u.school_id=s.id WHERE s.id=$1 GROUP BY s.id`,[id])).rows[0];if(!target)return json(res,404,{error:'Établissement introuvable'});if(target.platform_admin)return json(res,400,{error:'Le compte super-administrateur ne peut pas être désactivé'});if(safeText(b.confirmationName,{min:1,max:180})!==target.name)return json(res,400,{error:'Le nom de confirmation ne correspond pas'});const client=await pool.connect();try{await client.query('BEGIN');await client.query("UPDATE schools SET subscription_status='suspended',suspended_at=COALESCE(suspended_at,now()),deletion_requested_at=now() WHERE id=$1",[id]);await client.query('UPDATE users SET is_active=false,disabled_at=now() WHERE school_id=$1',[id]);await client.query('UPDATE sessions SET revoked_at=now() WHERE school_id=$1 AND revoked_at IS NULL',[id]);await client.query('INSERT INTO audit_logs(school_id,user_id,action,entity,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[me.schoolId,me.sub,'client.deletion_requested','school',id,JSON.stringify({confirmed:true,dataPreserved:true})]);await client.query('COMMIT');await authService.securityEvent(req,{type:'platform.client_deactivated',severity:'critical',outcome:'success',userId:me.sub,schoolId:me.schoolId,metadata:{targetSchoolId:id}});return json(res,200,{deactivated:true,dataPreserved:true})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()} }
    if(req.method==='PUT'&&/^\/api\/platform\/users\/[^/]+\/status$/.test(url.pathname)){if(!platform)return json(res,403,{error:'Accès super-administrateur requis'});authService.requireRecentAuthentication(me);const id=identifier(url.pathname.split('/')[4]),b=await body(req);if(typeof b.active!=='boolean')throw Error('invalid_body');const active=b.active;if(id===me.sub&&!active)return json(res,400,{error:'Votre propre compte ne peut pas être désactivé'});const target=(await pool.query('SELECT id,school_id,is_platform_admin FROM users WHERE id=$1',[id])).rows[0];if(!target)return json(res,404,{error:'Utilisateur introuvable'});if(target.is_platform_admin&&!active)return json(res,400,{error:'Le compte super-administrateur ne peut pas être désactivé'});await pool.query('UPDATE users SET is_active=$1,disabled_at=CASE WHEN $1 THEN NULL ELSE now() END WHERE id=$2',[active,id]);if(!active)await pool.query('UPDATE sessions SET revoked_at=now() WHERE user_id=$1 AND revoked_at IS NULL',[id]);await authService.securityEvent(req,{type:active?'account.enabled':'account.disabled',severity:'critical',outcome:'success',userId:me.sub,schoolId:me.schoolId,metadata:{targetUserId:id,targetSchoolId:target.school_id}});return json(res,200,{id,active});}
    if(route(req.method,url.pathname)==='GET /api/platform/subscription-payments') { if(!platform)return json(res,403,{error:'Accès super-administrateur requis'});const {limit,offset}=pagination(url.searchParams,{defaultLimit:100,maxLimit:200});const q=await pool.query('SELECT p.id,p.school_id,p.amount_minor,p.currency,p.method,p.reference,p.paid_at,p.coverage_end,p.notes,s.name school_name FROM subscription_payments p JOIN schools s ON s.id=p.school_id ORDER BY p.paid_at DESC,p.created_at DESC LIMIT $1 OFFSET $2',[limit,offset]);return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='POST /api/platform/subscription-payments') { if(!platform)return json(res,403,{error:'Accès super-administrateur requis'});authService.requireRecentAuthentication(me);const b=await body(req),schoolId=identifier(b.schoolId),amount=positiveInteger(b.amountMinor,{max:9_000_000_000_000}),method=oneOf(b.method,['Wave','Orange Money','Espèces','Virement','Carte bancaire','Chèque','Autre']),coverageEnd=isoDate(b.coverageEnd),paidAt=b.paidAt?isoTimestamp(b.paidAt):null;const client=await pool.connect();try{await client.query('BEGIN');const target=(await client.query(`SELECT s.id,s.currency,EXISTS(SELECT 1 FROM users u WHERE u.school_id=s.id AND u.is_platform_admin=true) platform_admin FROM schools s WHERE s.id=$1 FOR UPDATE`,[schoolId])).rows[0];if(!target)throw Error('Client introuvable');if(target.platform_admin)throw Error('Le compte super-administrateur est exempt');const currency=currencyCode(b.currency||target.currency||'XOF'),reference=safeText(b.reference||`ABN-${Date.now()}`,{min:3,max:120});const payment=(await client.query('INSERT INTO subscription_payments(school_id,amount_minor,currency,method,reference,paid_at,coverage_end,notes,recorded_by) VALUES($1,$2,$3,$4,$5,COALESCE($6::timestamptz,now()),$7,$8,$9) RETURNING id,school_id,amount_minor,currency,method,reference,paid_at,coverage_end,notes',[schoolId,String(amount),currency,method,reference,paidAt,coverageEnd,b.notes?safeText(b.notes,{max:500}):null,me.sub])).rows[0];await client.query("UPDATE schools SET subscription_status='active',subscription_due_date=$1,suspended_at=NULL WHERE id=$2",[coverageEnd,schoolId]);await client.query('INSERT INTO audit_logs(school_id,user_id,action,entity,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[me.schoolId,me.sub,'client.payment_recorded','subscription_payment',payment.id,JSON.stringify({clientSchoolId:schoolId,amountMinor:String(amount),currency:payment.currency,coverageEnd})]);await client.query('COMMIT');await authService.securityEvent(req,{type:'platform.payment_recorded',severity:'critical',outcome:'success',userId:me.sub,schoolId:me.schoolId,metadata:{targetSchoolId:schoolId,amountMinor:String(amount),currency:payment.currency}});return json(res,201,payment)}catch(e){await client.query('ROLLBACK');if(e.code==='23505')return json(res,409,{error:'Cette référence de paiement existe déjà pour ce client'});throw e}finally{client.release()} }
    if(route(req.method,url.pathname)==='GET /api/platform/subscription-payments.csv') { if(!platform)return json(res,403,{error:'Accès super-administrateur requis'});authService.requireRecentAuthentication(me);const q=await pool.query('SELECT p.paid_at,s.name,p.amount_minor,p.currency,p.method,p.reference,p.coverage_end,p.notes FROM subscription_payments p JOIN schools s ON s.id=p.school_id ORDER BY p.paid_at DESC LIMIT 5001');if(q.rows.length>5000)return json(res,413,{error:'Export trop volumineux. Réduisez la période.'});await authService.securityEvent(req,{type:'platform.export_created',severity:'warning',outcome:'success',userId:me.sub,schoolId:me.schoolId,metadata:{kind:'subscription_payments',rows:q.rowCount}});return csv(res,'paiements-abonnements.csv',[['Date','Établissement','Montant mineur','Devise','Mode','Référence','Abonnement payé jusqu’au','Notes'],...q.rows.map(x=>[x.paid_at.toISOString(),x.name,x.amount_minor,x.currency,x.method,x.reference,x.coverage_end,x.notes])]); }
    if(route(req.method,url.pathname)==='GET /api/students') { const {limit,offset}=pagination(url.searchParams,{defaultLimit:200,maxLimit:200});const q=await pool.query('SELECT id,matricule,first_name,last_name,class_name,guardian_name,guardian_phone,status,created_at FROM students WHERE school_id=$1 ORDER BY last_name,first_name LIMIT $2 OFFSET $3',[me.schoolId,limit,offset]); return json(res,200,q.rows); }
    if(req.method==='GET' && /^\/api\/students\/[^/]+\/statement$/.test(url.pathname)) { const id=url.pathname.split('/')[3];const student=(await pool.query('SELECT id,matricule,first_name,last_name,class_name,guardian_name,guardian_phone,status,created_at FROM students WHERE id=$1 AND school_id=$2',[id,me.schoolId])).rows[0];if(!student)return json(res,404,{error:'Élève introuvable'});const [invoices,payments]=await Promise.all([pool.query('SELECT i.id,i.label,i.amount_minor,i.currency,i.due_date,i.status,i.fee_type,i.created_at,COALESCE(p.paid_minor,0)::text paid_minor,(i.amount_minor-COALESCE(p.paid_minor,0))::text balance_minor FROM invoices i LEFT JOIN (SELECT invoice_id,sum(amount_minor) paid_minor FROM payments WHERE school_id=$2 GROUP BY invoice_id) p ON p.invoice_id=i.id WHERE i.student_id=$1 AND i.school_id=$2 ORDER BY i.due_date,i.created_at LIMIT 500',[id,me.schoolId]),pool.query('SELECT p.id,p.amount_minor,p.currency,p.method,p.reference,p.paid_at,i.label invoice_label,r.id receipt_id,r.number receipt_number FROM payments p LEFT JOIN invoices i ON i.id=p.invoice_id AND i.school_id=$2 LEFT JOIN receipts r ON r.payment_id=p.id AND r.school_id=$2 WHERE p.student_id=$1 AND p.school_id=$2 ORDER BY p.paid_at DESC LIMIT 500',[id,me.schoolId])]);return json(res,200,{student,invoices:invoices.rows,payments:payments.rows}); }
    if(route(req.method,url.pathname)==='POST /api/students/import') {
      authService.requireRecentAuthentication(me);
      const b=await body(req);
      const fileName=safeText(b.fileName,{min:1,max:120,pattern:/^[a-zA-Z0-9._ -]+$/}),mimeType=safeText(b.mimeType,{min:1,max:150,pattern:/^[a-z0-9.+-]+\/[a-z0-9.+-]+$/i});
      if(!b.fileBase64||!/^[a-zA-Z0-9+/=\r\n]+$/.test(b.fileBase64))return json(res,400,{error:'Fichier invalide'});
      const rate=(await pool.query(`INSERT INTO import_limits(school_id,user_id,window_started_at,attempts) VALUES($1,$2,now(),1)
        ON CONFLICT(school_id,user_id) DO UPDATE SET attempts=CASE WHEN import_limits.window_started_at<now()-interval '1 hour' THEN 1 ELSE import_limits.attempts+1 END,window_started_at=CASE WHEN import_limits.window_started_at<now()-interval '1 hour' THEN now() ELSE import_limits.window_started_at END RETURNING attempts`,[me.schoolId,me.sub])).rows[0];
      if(rate.attempts>10)return json(res,429,{error:'Limite d’import atteinte. Réessayez plus tard.'},{'retry-after':'3600'});
      const buffer=Buffer.from(b.fileBase64,'base64');
      if(buffer.length>3*1024*1024)return json(res,413,{error:'Fichier trop volumineux (3 Mo maximum)'});
      let rows;
      if(/\.xlsx$/i.test(fileName)){
        if(mimeType!=='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'||buffer[0]!==0x50||buffer[1]!==0x4b)return json(res,400,{error:'Contenu Excel invalide'});
        let archive;
        try{archive=unzipSync(buffer)}catch{return json(res,400,{error:'Contenu Excel invalide'})}
        const entries=Object.entries(archive),uncompressed=entries.reduce((total,[,value])=>total+value.byteLength,0);
        if(entries.length>300||uncompressed>20*1024*1024||entries.some(([name])=>/vbaProject\.bin|activeX|externalLinks|embeddings/i.test(name)))return json(res,400,{error:'Classeur actif ou structure Excel non autorisée'});
        if(entries.some(([name,value])=>/^xl\/worksheets\/.*\.xml$/i.test(name)&&/<f(?:\s|>)/i.test(Buffer.from(value).toString('utf8'))))return json(res,400,{error:'Les formules Excel ne sont pas autorisées'});
        rows=await readXlsxFile(buffer);
      }else if(/\.csv$/i.test(fileName)){
        if(!['text/csv','application/csv','application/vnd.ms-excel','text/plain'].includes(mimeType))return json(res,400,{error:'Type MIME CSV non autorisé'});
        const text=buffer.toString('utf8');if(text.includes('\0'))return json(res,400,{error:'Contenu CSV invalide'});rows=parseCsv(text.replace(/^\ufeff/,''));
      }else return json(res,400,{error:'Format accepté : .xlsx ou .csv'});
      if(rows.length<2)return json(res,400,{error:'Le fichier ne contient aucune ligne de données'});
      if(rows.length>1001)return json(res,400,{error:'Maximum 1 000 élèves par import'});
      if(rows.some(row=>!Array.isArray(row)||row.length>50||row.some(hasSpreadsheetFormula)))return json(res,400,{error:'Formules ou structure de cellule non autorisées'});
      const headers=rows[0].map(normalizeHeader);const aliases={matricule:['matricule','numero','numero_eleve','id_eleve'],firstName:['prenom','first_name','firstname'],lastName:['nom','last_name','lastname'],className:['classe','class','class_name','niveau'],guardianName:['parent','nom_parent','tuteur','responsable','guardian_name'],guardianPhone:['telephone','telephone_parent','tel','phone','guardian_phone']};const indexes={};for(const [key,names] of Object.entries(aliases))indexes[key]=headers.findIndex(h=>names.includes(h));if(indexes.firstName<0||indexes.lastName<0)return json(res,400,{error:'Colonnes obligatoires : prénom et nom'});
      const clean=rows.slice(1).map((r,i)=>({line:i+2,matricule:indexes.matricule>=0?String(r[indexes.matricule]??'').trim().slice(0,80):'',firstName:String(r[indexes.firstName]??'').trim().slice(0,120),lastName:String(r[indexes.lastName]??'').trim().slice(0,120),className:indexes.className>=0?String(r[indexes.className]??'').trim().slice(0,120):'',guardianName:indexes.guardianName>=0?String(r[indexes.guardianName]??'').trim().slice(0,180):'',guardianPhone:indexes.guardianPhone>=0?String(r[indexes.guardianPhone]??'').trim().slice(0,40):''}));const valid=clean.filter(x=>x.firstName&&x.lastName),invalid=clean.filter(x=>!x.firstName||!x.lastName).map(x=>x.line);
      if(b.preview)return json(res,200,{total:clean.length,valid:valid.length,invalidLines:invalid,sample:valid.slice(0,10)});
      if(!valid.length)return json(res,400,{error:'Aucune ligne valide à importer'});
      const client=await pool.connect();try{await client.query('BEGIN');const generated=await allocateMatricules(client,me.schoolId,valid.filter(x=>!x.matricule).length);let gi=0;valid.forEach(x=>{if(!x.matricule)x.matricule=generated[gi++]});const params=[],values=[];valid.forEach((x,i)=>{const n=i*7;values.push(`($${n+1},$${n+2},$${n+3},$${n+4},$${n+5},$${n+6},$${n+7})`);params.push(me.schoolId,x.matricule,x.firstName,x.lastName,x.className||null,x.guardianName||null,x.guardianPhone||null)});const q=await client.query(`INSERT INTO students(school_id,matricule,first_name,last_name,class_name,guardian_name,guardian_phone) VALUES ${values.join(',')} ON CONFLICT(school_id,matricule) DO NOTHING RETURNING id`,params);await client.query('INSERT INTO audit_logs(school_id,user_id,action,entity,metadata) VALUES($1,$2,$3,$4,$5)',[me.schoolId,me.sub,'students.imported','student',JSON.stringify({imported:q.rowCount,duplicates:valid.length-q.rowCount,invalid:invalid.length,mimeType})]);await client.query('COMMIT');await authService.securityEvent(req,{type:'students.imported',severity:'warning',outcome:'success',userId:me.sub,schoolId:me.schoolId,metadata:{imported:q.rowCount,invalid:invalid.length}});return json(res,201,{imported:q.rowCount,duplicates:valid.length-q.rowCount,invalid:invalid.length});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}
    }
    if(route(req.method,url.pathname)==='POST /api/students') { const b=await body(req),firstName=safeText(b.firstName,{min:1,max:120}),lastName=safeText(b.lastName,{min:1,max:120}),className=b.className?safeText(b.className,{max:120}):null,guardianName=b.guardianName?safeText(b.guardianName,{max:180}):null,guardianPhone=b.guardianPhone?safeText(b.guardianPhone,{max:40}):null;const client=await pool.connect();try{await client.query('BEGIN');const matricule=b.matricule?safeText(b.matricule,{min:1,max:80}):await allocateMatricules(client,me.schoolId,1).then(x=>x[0]);const q=await client.query('INSERT INTO students(school_id,matricule,first_name,last_name,class_name,guardian_name,guardian_phone) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,matricule,first_name,last_name,class_name,guardian_name,guardian_phone,status,created_at',[me.schoolId,matricule,firstName,lastName,className,guardianName,guardianPhone]);await client.query('COMMIT');return json(res,201,q.rows[0])}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()} }
    if(req.method==='PUT' && /^\/api\/students\/[^/]+$/.test(url.pathname)) { const id=url.pathname.split('/').pop(); const b=await body(req),matricule=safeText(b.matricule,{min:1,max:80}),firstName=safeText(b.firstName,{min:1,max:120}),lastName=safeText(b.lastName,{min:1,max:120}); const q=await pool.query('UPDATE students SET matricule=$1,first_name=$2,last_name=$3,class_name=$4,guardian_name=$5,guardian_phone=$6 WHERE id=$7 AND school_id=$8 RETURNING id,matricule,first_name,last_name,class_name,guardian_name,guardian_phone,status,created_at',[matricule,firstName,lastName,b.className?safeText(b.className,{max:120}):null,b.guardianName?safeText(b.guardianName,{max:180}):null,b.guardianPhone?safeText(b.guardianPhone,{max:40}):null,id,me.schoolId]); if(!q.rows[0]) return json(res,404,{error:'Élève introuvable'}); await pool.query('INSERT INTO audit_logs(school_id,user_id,action,entity,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[me.schoolId,me.sub,'student.updated','student',id,JSON.stringify({fields:['identity','class','guardian']})]); return json(res,200,q.rows[0]); }
    if(route(req.method,url.pathname)==='GET /api/academic-years') { const {limit,offset}=pagination(url.searchParams,{defaultLimit:50,maxLimit:100});const q=await pool.query('SELECT id,label,starts_on,ends_on,is_current FROM academic_years WHERE school_id=$1 ORDER BY starts_on DESC LIMIT $2 OFFSET $3',[me.schoolId,limit,offset]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='POST /api/academic-years') { const b=await body(req),label=safeText(b.label,{min:3,max:50}),startsOn=isoDate(b.startsOn),endsOn=isoDate(b.endsOn);if(endsOn<=startsOn)return json(res,400,{error:'La date de fin doit suivre la date de début'});const q=await pool.query('INSERT INTO academic_years(school_id,label,starts_on,ends_on,is_current) VALUES($1,$2,$3,$4,$5) RETURNING id,label,starts_on,ends_on,is_current',[me.schoolId,label,startsOn,endsOn,Boolean(b.isCurrent)]); return json(res,201,q.rows[0]); }
    if(route(req.method,url.pathname)==='GET /api/classes') { const {limit,offset}=pagination(url.searchParams,{defaultLimit:200,maxLimit:200});const q=await pool.query('SELECT c.id,c.academic_year_id,c.name,c.level,c.capacity,a.label academic_year FROM classes c JOIN academic_years a ON a.id=c.academic_year_id WHERE c.school_id=$1 ORDER BY c.name LIMIT $2 OFFSET $3',[me.schoolId,limit,offset]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='POST /api/classes') { const b=await body(req),academicYearId=identifier(b.academicYearId),name=safeText(b.name,{min:1,max:120}),level=b.level?safeText(b.level,{max:80}):null,capacity=b.capacity?positiveInteger(b.capacity,{max:10000}):null;const q=await pool.query('INSERT INTO classes(school_id,academic_year_id,name,level,capacity) SELECT $1,$2,$3,$4,$5 WHERE EXISTS(SELECT 1 FROM academic_years WHERE id=$2 AND school_id=$1) RETURNING id,academic_year_id,name,level,capacity',[me.schoolId,academicYearId,name,level,capacity]); return q.rows[0]?json(res,201,q.rows[0]):json(res,404,{error:'Année scolaire introuvable'}); }
    if(route(req.method,url.pathname)==='GET /api/guardians') { const {limit,offset}=pagination(url.searchParams,{defaultLimit:200,maxLimit:200});const q=await pool.query('SELECT id,full_name,phone,email,preferred_language,created_at FROM guardians WHERE school_id=$1 ORDER BY full_name LIMIT $2 OFFSET $3',[me.schoolId,limit,offset]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='POST /api/guardians') { const b=await body(req),fullName=safeText(b.fullName,{min:2,max:180}),phone=b.phone?safeText(b.phone,{max:40}):null,email=b.email?emailAddress(b.email):null,language=oneOf(b.preferredLanguage||'fr',['fr','wo','en']);const q=await pool.query('INSERT INTO guardians(school_id,full_name,phone,email,preferred_language) VALUES($1,$2,$3,$4,$5) RETURNING id,full_name,phone,email,preferred_language,created_at',[me.schoolId,fullName,phone,email,language]); return json(res,201,q.rows[0]); }
    if(route(req.method,url.pathname)==='POST /api/enrollments') { const b=await body(req),studentId=identifier(b.studentId),classId=identifier(b.classId),academicYearId=identifier(b.academicYearId),status=oneOf(b.status||'active',['active','completed','cancelled']);const client=await pool.connect(); try { await client.query('BEGIN'); const e=(await client.query('INSERT INTO enrollments(school_id,student_id,class_id,academic_year_id,status) SELECT $1,$2,$3,$4,$5 WHERE EXISTS(SELECT 1 FROM students WHERE id=$2 AND school_id=$1) AND EXISTS(SELECT 1 FROM classes WHERE id=$3 AND academic_year_id=$4 AND school_id=$1) AND EXISTS(SELECT 1 FROM academic_years WHERE id=$4 AND school_id=$1) RETURNING id,student_id,class_id,academic_year_id,status,enrolled_at',[me.schoolId,studentId,classId,academicYearId,status])).rows[0]; if(!e){await client.query('ROLLBACK');return json(res,404,{error:'Élève, classe ou année scolaire introuvable'})} await client.query('UPDATE students SET class_name=(SELECT name FROM classes WHERE id=$1 AND school_id=$2) WHERE id=$3 AND school_id=$2',[classId,me.schoolId,studentId]); await client.query('COMMIT'); return json(res,201,e); } catch(e){await client.query('ROLLBACK');throw e;} finally{client.release();} }
    if(route(req.method,url.pathname)==='POST /api/student-guardians') { const b=await body(req),studentId=identifier(b.studentId),guardianId=identifier(b.guardianId),relationship=safeText(b.relationship||'parent',{min:2,max:60});const q=await pool.query('INSERT INTO student_guardians(student_id,guardian_id,relationship,is_primary) SELECT $1,$2,$3,$4 WHERE EXISTS(SELECT 1 FROM students WHERE id=$1 AND school_id=$5) AND EXISTS(SELECT 1 FROM guardians WHERE id=$2 AND school_id=$5) RETURNING student_id,guardian_id,relationship,is_primary',[studentId,guardianId,relationship,Boolean(b.isPrimary),me.schoolId]); return q.rows[0]?json(res,201,q.rows[0]):json(res,404,{error:'Élève ou parent introuvable'}); }
    if(route(req.method,url.pathname)==='GET /api/invoices') { const {limit,offset}=pagination(url.searchParams,{defaultLimit:200,maxLimit:200});const q=await pool.query('SELECT i.id,i.student_id,i.label,i.amount_minor,i.currency,i.due_date,i.status,i.fee_type,i.created_at,s.first_name,s.last_name,s.matricule,COALESCE((SELECT sum(p.amount_minor) FROM payments p WHERE p.invoice_id=i.id AND p.school_id=$1),0)::text paid_minor FROM invoices i JOIN students s ON s.id=i.student_id AND s.school_id=$1 WHERE i.school_id=$1 ORDER BY i.due_date LIMIT $2 OFFSET $3',[me.schoolId,limit,offset]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='POST /api/invoices/bulk') { const b=await body(req),types=['tuition','registration','uniform','transport','other'],label=safeText(b.label,{min:1,max:180}),amount=positiveInteger(b.amountMinor,{max:9_000_000_000_000}),currency=currencyCode(b.currency),dueDate=isoDate(b.dueDate),feeType=oneOf(b.feeType||'other',types);const q=await pool.query("INSERT INTO invoices(school_id,student_id,label,amount_minor,currency,due_date,fee_type) SELECT $1,s.id,$2,$3,$4,$5,$6 FROM students s WHERE s.school_id=$1 AND s.status='active' RETURNING id",[me.schoolId,label,String(amount),currency,dueDate,feeType]);await pool.query('INSERT INTO audit_logs(school_id,user_id,action,entity,metadata) VALUES($1,$2,$3,$4,$5)',[me.schoolId,me.sub,'invoices.bulk_created','invoice',JSON.stringify({count:q.rowCount,label,amountMinor:String(amount),currency})]);return json(res,201,{created:q.rowCount}); }
    if(route(req.method,url.pathname)==='POST /api/invoices') { const b=await body(req),types=['tuition','registration','uniform','transport','other'],studentId=identifier(b.studentId),label=safeText(b.label,{min:1,max:180}),amount=positiveInteger(b.amountMinor,{max:9_000_000_000_000}),currency=currencyCode(b.currency),dueDate=isoDate(b.dueDate),feeType=oneOf(b.feeType||'other',types);const q=await pool.query('INSERT INTO invoices(school_id,student_id,label,amount_minor,currency,due_date,fee_type) SELECT $1,$2,$3,$4,$5,$6,$7 WHERE EXISTS(SELECT 1 FROM students WHERE id=$2 AND school_id=$1) RETURNING id,student_id,label,amount_minor,currency,due_date,status,fee_type,created_at',[me.schoolId,studentId,label,String(amount),currency,dueDate,feeType]); return q.rows[0]?json(res,201,q.rows[0]):json(res,404,{error:'Élève introuvable'}); }
    if(route(req.method,url.pathname)==='POST /api/payments') {
      authService.requireRecentAuthentication(me);
      const b=await body(req),invoiceId=identifier(b.invoiceId),amountNumber=positiveInteger(b.amountMinor,{max:9_000_000_000_000}),currency=currencyCode(b.currency),methods=['Espèces','Wave','Orange Money','Virement','Carte bancaire','Chèque','Autre'];
      if(!methods.includes(b.method))return json(res,400,{error:'Données de paiement invalides'});
      const amount=BigInt(amountNumber);
      const client=await pool.connect();
      try {
        await client.query('BEGIN');
        const inv=(await client.query('SELECT id,student_id,amount_minor,currency,status FROM invoices WHERE id=$1 AND school_id=$2 FOR UPDATE',[invoiceId,me.schoolId])).rows[0];
        if(!inv){await client.query('ROLLBACK');return json(res,404,{error:'Échéance introuvable'})}
        if(inv.status==='cancelled'||String(inv.currency).trim().toUpperCase()!==currency){await client.query('ROLLBACK');return json(res,400,{error:'Paiement incompatible avec cette échéance'})}
        const previous=BigInt((await client.query('SELECT COALESCE(sum(amount_minor),0)::text total FROM payments WHERE invoice_id=$1 AND school_id=$2',[inv.id,me.schoolId])).rows[0].total),remaining=BigInt(inv.amount_minor)-previous;
        if(amount>remaining){await client.query('ROLLBACK');return json(res,400,{error:'Le montant dépasse le solde restant'})}
        const reference=safeText(b.reference||`PAY-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${String(Date.now()).slice(-6)}-${crypto.randomBytes(2).toString('hex').toUpperCase()}`,{min:3,max:120});
        const p=(await client.query('INSERT INTO payments(school_id,student_id,invoice_id,amount_minor,currency,method,reference) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,student_id,invoice_id,amount_minor,currency,method,reference,paid_at',[me.schoolId,inv.student_id,inv.id,amount.toString(),currency,b.method,reference])).rows[0];
        const total=previous+amount,status=total>=BigInt(inv.amount_minor)?'paid':'partial';
        await client.query('UPDATE invoices SET status=$1 WHERE id=$2 AND school_id=$3',[status,inv.id,me.schoolId]);
        const receiptNumber=`SCP-${new Date().getUTCFullYear()}-${String(Date.now()).slice(-8)}-${crypto.randomBytes(2).toString('hex').toUpperCase()}`;
        const receipt=(await client.query('INSERT INTO receipts(school_id,payment_id,number) VALUES($1,$2,$3) RETURNING id,payment_id,number,issued_at',[me.schoolId,p.id,receiptNumber])).rows[0];
        await client.query('INSERT INTO audit_logs(school_id,user_id,action,entity,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[me.schoolId,me.sub,'payment.created','payment',p.id,JSON.stringify({amountMinor:amount.toString(),currency,method:b.method})]);
        await client.query('COMMIT');
        await authService.securityEvent(req,{type:'payment.created',severity:'warning',outcome:'success',userId:me.sub,schoolId:me.schoolId,metadata:{paymentId:p.id,amountMinor:amount.toString(),currency}});
        return json(res,201,{payment:p,receipt,invoiceStatus:status});
      } catch(e){await client.query('ROLLBACK');throw e;} finally{client.release();}
    }
    if(route(req.method,url.pathname)==='GET /api/receipts') { const {limit,offset}=pagination(url.searchParams,{defaultLimit:200,maxLimit:200});const q=await pool.query('SELECT r.id,r.number,r.issued_at,p.paid_at,p.amount_minor,p.currency,p.method,p.reference,s.matricule,s.first_name,s.last_name,s.class_name,i.label invoice_label,sc.name school_name FROM receipts r JOIN payments p ON p.id=r.payment_id AND p.school_id=$1 JOIN students s ON s.id=p.student_id AND s.school_id=$1 LEFT JOIN invoices i ON i.id=p.invoice_id AND i.school_id=$1 JOIN schools sc ON sc.id=r.school_id WHERE r.school_id=$1 ORDER BY r.issued_at DESC LIMIT $2 OFFSET $3',[me.schoolId,limit,offset]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='GET /api/collections/overdue') { const q=await pool.query(`SELECT i.id,i.label,i.amount_minor::text,i.currency,i.due_date,i.status,(CURRENT_DATE-i.due_date)::int days_overdue,s.matricule,s.first_name,s.last_name,COALESCE(sum(p.amount_minor),0)::text paid_minor,(i.amount_minor-COALESCE(sum(p.amount_minor),0))::text balance_minor FROM invoices i JOIN students s ON s.id=i.student_id LEFT JOIN payments p ON p.invoice_id=i.id WHERE i.school_id=$1 AND i.status IN ('unpaid','partial') AND i.due_date<CURRENT_DATE GROUP BY i.id,s.id ORDER BY days_overdue DESC,balance_minor DESC LIMIT 500`,[me.schoolId]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='POST /api/reminders') { const b=await body(req),guardianId=identifier(b.guardianId),invoiceId=identifier(b.invoiceId),channel=oneOf(b.channel,['email','sms','whatsapp']),message=safeText(b.message,{min:1,max:1000}),scheduledAt=b.scheduledAt?isoTimestamp(b.scheduledAt):null;const q=await pool.query(`INSERT INTO reminders(school_id,guardian_id,invoice_id,channel,message,scheduled_at) SELECT $1,$2,$3,$4,$5,COALESCE($6::timestamptz,now()) WHERE EXISTS(SELECT 1 FROM guardians WHERE id=$2 AND school_id=$1) AND EXISTS(SELECT 1 FROM invoices WHERE id=$3 AND school_id=$1) RETURNING id,guardian_id,invoice_id,channel,message,status,scheduled_at,sent_at,created_at`,[me.schoolId,guardianId,invoiceId,channel,message,scheduledAt]); return q.rows[0]?json(res,201,q.rows[0]):json(res,404,{error:'Parent ou échéance introuvable'}); }
    if(route(req.method,url.pathname)==='GET /api/reminders') { const {limit,offset}=pagination(url.searchParams,{defaultLimit:200,maxLimit:200});const q=await pool.query('SELECT r.id,r.guardian_id,r.invoice_id,r.channel,r.message,r.status,r.scheduled_at,r.sent_at,r.created_at,g.full_name guardian_name,i.label invoice_label FROM reminders r JOIN guardians g ON g.id=r.guardian_id AND g.school_id=$1 JOIN invoices i ON i.id=r.invoice_id AND i.school_id=$1 WHERE r.school_id=$1 ORDER BY r.scheduled_at DESC LIMIT $2 OFFSET $3',[me.schoolId,limit,offset]); return json(res,200,q.rows); }
    if(route(req.method,url.pathname)==='POST /api/parent-links') { const b=await body(req),guardianId=identifier(b.guardianId); const exists=(await pool.query('SELECT 1 FROM guardians WHERE id=$1 AND school_id=$2',[guardianId,me.schoolId])).rowCount; if(!exists) return json(res,404,{error:'Parent introuvable'}); const token=crypto.randomBytes(32).toString('base64url'); const hash=crypto.createHash('sha256').update(token).digest('hex'); const hours=positiveInteger(b.expiresInHours||72,{max:720}); const record=(await pool.query(`INSERT INTO parent_portal_tokens(school_id,guardian_id,token_hash,expires_at) VALUES($1,$2,$3,now()+($4||' hours')::interval) RETURNING id,guardian_id,expires_at`,[me.schoolId,guardianId,hash,String(hours)])).rows[0]; return json(res,201,{...record,accessCode:token,loginPath:'/connexion-parent'}); }
    if(route(req.method,url.pathname)==='GET /api/exports/payments.csv') { authService.requireRecentAuthentication(me);const [payments,summary]=await Promise.all([pool.query('SELECT p.paid_at,s.matricule,s.first_name,s.last_name,p.amount_minor,p.currency,p.method,p.reference,r.number receipt FROM payments p JOIN students s ON s.id=p.student_id AND s.school_id=$1 LEFT JOIN receipts r ON r.payment_id=p.id AND r.school_id=$1 WHERE p.school_id=$1 ORDER BY p.paid_at DESC LIMIT 5001',[me.schoolId]),pool.query('SELECT i.currency,COALESCE(sum(i.amount_minor),0)::text expected_minor,COALESCE(sum(p.paid_minor),0)::text paid_minor FROM invoices i LEFT JOIN (SELECT invoice_id,sum(amount_minor) paid_minor FROM payments WHERE school_id=$1 GROUP BY invoice_id) p ON p.invoice_id=i.id WHERE i.school_id=$1 AND i.status<>\'cancelled\' GROUP BY i.currency ORDER BY i.currency',[me.schoolId])]);if(payments.rows.length>5000)return json(res,413,{error:'Export trop volumineux. Réduisez la période.'});await pool.query('INSERT INTO audit_logs(school_id,user_id,action,entity,metadata) VALUES($1,$2,$3,$4,$5)',[me.schoolId,me.sub,'payments.exported','payment',JSON.stringify({rows:payments.rowCount})]);await authService.securityEvent(req,{type:'payments.exported',severity:'warning',outcome:'success',userId:me.sub,schoolId:me.schoolId,metadata:{rows:payments.rowCount}});const rows=[['BILAN DES PAIEMENTS'],['Devise','Montant attendu (mineur)','Montant encaissé (mineur)','Reste à recevoir (mineur)'],...summary.rows.map(x=>[x.currency,x.expected_minor,x.paid_minor,(BigInt(x.expected_minor)-BigInt(x.paid_minor)).toString()]),[],['DÉTAIL DES ENCAISSEMENTS'],['Date','Matricule','Prénom','Nom','Montant mineur','Devise','Méthode','Référence','Reçu'],...payments.rows.map(x=>[x.paid_at.toISOString(),x.matricule,x.first_name,x.last_name,x.amount_minor,x.currency,x.method,x.reference,x.receipt])];return csv(res,'bilan-paiements.csv',rows); }
    if(route(req.method,url.pathname)==='GET /api/exports/students.csv') { authService.requireRecentAuthentication(me);const q=await pool.query('SELECT matricule,first_name,last_name,class_name,guardian_name,guardian_phone,status,created_at FROM students WHERE school_id=$1 ORDER BY last_name,first_name LIMIT 5001',[me.schoolId]);if(q.rows.length>5000)return json(res,413,{error:'Export trop volumineux. Réduisez la sélection.'});await pool.query('INSERT INTO audit_logs(school_id,user_id,action,entity,metadata) VALUES($1,$2,$3,$4,$5)',[me.schoolId,me.sub,'students.exported','student',JSON.stringify({rows:q.rowCount})]);await authService.securityEvent(req,{type:'students.exported',severity:'warning',outcome:'success',userId:me.sub,schoolId:me.schoolId,metadata:{rows:q.rowCount}});return csv(res,'archive-eleves.csv',[['Matricule','Prénom','Nom','Classe','Parent','Téléphone','Statut','Date de création'],...q.rows.map(x=>[x.matricule,x.first_name,x.last_name,x.class_name,x.guardian_name,x.guardian_phone,x.status,x.created_at.toISOString()])]); }
    if(route(req.method,url.pathname)==='GET /api/dashboard') { const q=await pool.query(`SELECT COALESCE(sum(amount_minor),0)::text expected,COALESCE(sum(amount_minor) FILTER(WHERE status='paid'),0)::text paid,COUNT(*) FILTER(WHERE status!='paid')::int unpaid_count FROM invoices WHERE school_id=$1`,[me.schoolId]); return json(res,200,q.rows[0]); }
    return json(res,404,{error:'Route introuvable'});
  } catch(e){ const known={unauthorized:[401,'Authentification requise'],unsupported_media:[415,'Type de contenu non accepté'],body_too_large:[413,'Requête trop volumineuse'],invalid_body:[400,'Données invalides'],weak_password:[400,'Le mot de passe ne respecte pas la politique de sécurité'],invalid_credentials:[401,'Vérification impossible'],reauthentication_required:[428,'Réauthentification récente requise'],invalid_mfa:[401,'Code de vérification invalide'],mfa_unavailable:[503,'MFA temporairement indisponible'],invalid_reset_token:[400,'Lien de récupération invalide ou expiré'],password_reset_unavailable:[503,'Récupération temporairement indisponible'],alerting_unavailable:[503,'Alertes temporairement indisponibles']};const databaseKnown={'22P02':[400,'Données invalides'],'22007':[400,'Date invalide'],'22008':[400,'Date invalide'],'22003':[400,'Valeur numérique invalide'],'23503':[400,'Référence invalide'],'23505':[409,'Cette donnée existe déjà'],'23514':[400,'Données invalides']};const response=known[e.message]||databaseKnown[e.code]||[500,'Erreur interne'];if(response[0]===500)console.error('request_failed',{name:e?.name,code:e?.code});return json(res,response[0],{error:response[1]}); }
};

if (!process.env.VERCEL) {
  http.createServer(handler).listen(port,'0.0.0.0',()=>console.log(`SCOLARIS API : http://localhost:${port}`));
}

export default handler;
export const closeDatabase = () => pool.end();
