import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { amySnapshot,resolveAmyFilters } from '../src/amy-service.js';
import { findAmySources } from '../src/amy-knowledge.js';
import { createReminderService } from '../src/reminder-service.js';
import { createWaveService } from '../src/wave-service.js';

export async function verifyImprovements({pool,request,cookie,schoolA,schoolB}) {
  const headers={cookie,'content-type':'application/json'};
  const post=async(path,value)=>request(path,{method:'POST',headers,body:JSON.stringify(value)});
  const created=await post('/api/amy/documents',{title:'Procédure fictive de recouvrement',content:'La procédure de recouvrement prévoit une vérification comptable avant toute relance. Aucun message ne part sans validation.'});
  assert.equal(created.status,201);const document=await created.json();
  const sources=await findAmySources(pool,schoolA,'Quelle procédure de recouvrement ?');assert.equal(sources[0].reference,'D1');assert.equal(sources[0].title,document.title);
  assert.deepEqual(await findAmySources(pool,schoolB,'recouvrement'),[]);
  const docs=await (await request('/api/amy/documents',{headers})).json();assert.equal(docs.canManage,true);assert.ok(docs.documents.some(d=>d.id===document.id));
  assert.equal((await post('/api/amy/documents',{title:'x',content:'x',schoolId:schoolB})).status,400);
  const owner=(await pool.query("SELECT id FROM users WHERE school_id=$1 AND role='owner' AND NOT is_platform_admin LIMIT 1",[schoolA])).rows[0];
  const student=(await pool.query("INSERT INTO students(school_id,matricule,first_name,last_name) VALUES($1,'IMPROVE-001','Élève','Pagination') RETURNING id",[schoolA])).rows[0];
  const year=(await pool.query("INSERT INTO academic_years(school_id,label,starts_on,ends_on) VALUES($1,'Améliorations test','2027-01-01','2027-12-31') RETURNING id",[schoolA])).rows[0];
  const schoolClass=(await pool.query("INSERT INTO classes(school_id,academic_year_id,name) VALUES($1,$2,'Classe test améliorations') RETURNING id",[schoolA,year.id])).rows[0];
  const invoice=(await pool.query("INSERT INTO invoices(school_id,student_id,label,amount_minor,currency,due_date,academic_year_id,class_id,amount_expected_xof,amount_due_xof,balance_xof) VALUES($1,$2,'Échéance améliorations',1500000,'XOF','2027-02-01',$3,$4,15000,15000,15000) RETURNING *",[schoolA,student.id,year.id,schoolClass.id])).rows[0];
  const filters={academicYearId:year.id,classId:schoolClass.id,from:'2027-02-01',to:'2027-02-01'},selection=await resolveAmyFilters(pool,schoolA,filters);
  const snapshot=await amySnapshot(pool,schoolA,filters,selection);assert.equal(snapshot.invoiceCount,1);assert.equal(snapshot.expectedXof,'15000');assert.equal(snapshot.scope,'filtered');
  await assert.rejects(resolveAmyFilters(pool,schoolB,filters));
  const page=await (await request('/api/students/search?q=IMPROVE&limit=1',{headers})).json();assert.equal(page.total,1);assert.equal(page.students[0].id,student.id);
  const open=await (await request('/api/invoices/open?q=IMPROVE&limit=1',{headers})).json();assert.equal(open.total,1);assert.equal(open.invoices[0].id,invoice.id);assert.equal(open.invoices[0].balance_xof,'15000');
  const next=await (await request('/api/invoices/open?q=IMPROVE&limit=1&offset=1',{headers})).json();assert.equal(next.total,1);assert.deepEqual(next.invoices,[]);
  const literal=await (await request('/api/invoices/open?q=%25',{headers})).json();assert.equal(literal.total,0);
  const guardian=(await pool.query("INSERT INTO guardians(school_id,full_name,email) VALUES($1,'Parent fictif','parent@example.test') RETURNING id",[schoolA])).rows[0];
  await pool.query("INSERT INTO student_guardians(school_id,student_id,guardian_id,relationship) VALUES($1,$2,$3,'parent')",[schoolA,student.id,guardian.id]);
  const input={guardianId:guardian.id,invoiceId:invoice.id,channel:'email',message:'Relance fictive',idempotencyKey:crypto.randomUUID()};
  const draft=await (await post('/api/reminders',input)).json(),duplicate=await (await post('/api/reminders',input)).json();assert.equal(draft.id,duplicate.id);assert.equal(draft.approved_at,null);
  let sent=0,approvalStatus,approvalInput={recipient:'parent@example.test'};const reminder=createReminderService({pool,json:(_res,status)=>{approvalStatus=status;},body:async()=>approvalInput,identifier:x=>x,env:{REMINDER_DELIVERY_ENABLED:'true',RESEND_API_KEY:crypto.randomBytes(32).toString('hex'),RESEND_FROM_EMAIL:'test@example.test'},fetchImpl:async()=>{sent++;return Response.json({id:crypto.randomUUID()});}});
  await reminder.dispatch(schoolA,draft.id);assert.equal(sent,0);
  const approve=async id=>reminder.router({method:'POST'},{},new URL('https://scolaris.test/api/reminders/'+id+'/approve'),{sub:owner.id,schoolId:schoolA,role:'owner'});
  approvalInput={recipient:'changed@example.test'};await approve(draft.id);assert.equal(approvalStatus,409);
  approvalInput={recipient:'parent@example.test'};await approve(draft.id);assert.equal(approvalStatus,200);
  await Promise.all([reminder.dispatch(schoolA,draft.id),reminder.dispatch(schoolA,draft.id)]);assert.equal(sent,1);
  const delivered=(await pool.query('SELECT status,delivery_status FROM reminders WHERE id=$1',[draft.id])).rows[0];assert.equal(delivered.status,'sent');assert.equal(delivered.delivery_status,'accepted');
  const changedRecipient=await (await post('/api/reminders',{...input,idempotencyKey:crypto.randomUUID()})).json();
  await approve(changedRecipient.id);assert.equal(approvalStatus,200);
  await pool.query("UPDATE guardians SET email='updated@example.test' WHERE id=$1",[guardian.id]);
  await reminder.dispatch(schoolA,changedRecipient.id);assert.equal(sent,1);
  assert.equal((await pool.query('SELECT status FROM reminders WHERE id=$1',[changedRecipient.id])).rows[0].status,'cancelled');
  const foreignActor=(await pool.query('SELECT id FROM users WHERE school_id=$1 LIMIT 1',[schoolB])).rows[0].id;
  await assert.rejects(pool.query('UPDATE amy_documents SET created_by=$2 WHERE id=$1',[document.id,foreignActor]),/invalid school actor/);
  const checkout=(await pool.query('INSERT INTO online_checkouts(school_id,invoice_id,created_by,amount_xof) VALUES($1,$2,$3,15000) RETURNING *',[schoolA,invoice.id,owner.id])).rows[0];
  const service=createWaveService({pool,json:()=>{},body:async()=>({}),identifier:x=>x});
  const completed={id:'cos-'+crypto.randomBytes(8).toString('hex'),client_reference:checkout.id,amount:'15000',currency:'XOF',wave_launch_url:'https://pay.wave.com/c/test',checkout_status:'complete',payment_status:'succeeded',transaction_id:'TEST-'+crypto.randomUUID(),when_completed:new Date().toISOString()};
  await assert.rejects(pool.query('UPDATE online_checkouts SET created_by=$2 WHERE id=$1',[checkout.id,foreignActor]),/invalid school actor/);
  await Promise.all([service.confirm(checkout,completed),service.confirm(checkout,completed)]);
  assert.equal((await pool.query('SELECT count(*)::int n FROM student_payment_batches WHERE school_id=$1 AND reference=$2',[schoolA,'WAVE-'+completed.transaction_id])).rows[0].n,1);
  assert.equal((await pool.query('SELECT financial_status FROM invoices WHERE id=$1',[invoice.id])).rows[0].financial_status,'paid');
  assert.equal((await (await request('/api/invoices/open?q=IMPROVE',{headers})).json()).total,0);
  const reconciled=(await pool.query('SELECT status,receipt_number FROM online_checkouts WHERE id=$1',[checkout.id])).rows[0];assert.equal(reconciled.status,'confirmed');assert.ok(reconciled.receipt_number);
  const other=(await pool.query("INSERT INTO invoices(school_id,student_id,label,amount_minor,currency,due_date,amount_expected_xof,amount_due_xof,balance_xof) VALUES($1,$2,'Solde modifié',1000000,'XOF',CURRENT_DATE,10000,10000,10000) RETURNING *",[schoolA,student.id])).rows[0];
  const review=(await pool.query('INSERT INTO online_checkouts(school_id,invoice_id,created_by,amount_xof) VALUES($1,$2,$3,10000) RETURNING *',[schoolA,other.id,owner.id])).rows[0];
  await pool.query('UPDATE invoices SET amount_due_xof=5000,balance_xof=5000,discount_xof=5000 WHERE id=$1',[other.id]);
  await service.confirm(review,{...completed,id:'cos-'+crypto.randomBytes(8).toString('hex'),client_reference:review.id,amount:'10000',transaction_id:'TEST-'+crypto.randomUUID()});
  assert.equal((await pool.query('SELECT status FROM online_checkouts WHERE id=$1',[review.id])).rows[0].status,'review');
  assert.equal((await request('/api/online-payments',{headers})).status,200);
  assert.equal((await post('/api/online-payments',{invoiceId:other.id})).status,503);
  assert.equal((await request('/api/amy/documents/'+document.id,{method:'DELETE',headers,body:'{}'})).status,200);
  assert.deepEqual(await findAmySources(pool,schoolA,'procédure recouvrement'),[]);
}
